[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.14", features = ["ws"] }
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
futures = "0.3.31"
colored = "3.0.0"
eyre = "0.6.12"
chrono = "0.4.39"
